version: 2
jobs:
  build:
    machine: true
    steps:
        - checkout
        - run: ps axf
        - run: uname -a
        - run: lscpu
        - run: free
        - run: cat /etc/issue
        - run: docker -v
