version: 2
jobs:
  build:
    machine: true
    steps:
        - checkout
        - run: 
            name: Provision swarm cluster
            command: |
                ./test/swarm-deploy.sh deploy 2
                cat "$HOME"/nuvla-test-host
                export ip=$(cat "$HOME"/nuvla-test-host)
                ./test/wait-avail.sh https://$ip/api/cloud-entry-point 2
        - run: 
            name: Tests
            command: |
                cd functional-tests
                export NUVLA_INSECURE=TRUE
                export NUVLA_HOST=$(cat $HOME/nuvla-test-host)
                lein do clean, test
        - run: 
            name: Destroy swarm cluster
            command: |
                ./test/swarm-deploy.sh terminate
            when: always
