version: '3'
services:
  es:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.2.4
    container_name: elasticsearch
    restart: unless-stopped
    ports:
     - "9200:9200"
    environment:
     - cluster.name=elasticsearch
     - xpack.security.enabled=false
     - discovery.type=single-node
     - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
  zk:
    image: zookeeper:latest
    container_name: zookeeper
    restart: unless-stopped
    ports:
     - "2181:2181"
    environment:
     - ZOO_MY_ID=3
