version: '3'
services:
  proxy:
    image: traefik:latest
    restart: unless-stopped
    command: --api --web --docker --docker.exposedByDefault=false --loglevel=info
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./traefik/traefik.toml:/traefik.toml
      - ./traefik/nuvla.crt:/nuvla.crt
      - ./traefik/nuvla.key:/nuvla.key
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"
  es:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.2.4
    restart: unless-stopped
    expose:
      - "9200"
      - "9300"
    environment:
      - cluster.name=elasticsearch
      - xpack.security.enabled=false
      - discovery.type=single-node
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
  zk:
    image: zookeeper:latest
    restart: unless-stopped
    expose:
      - "2181"
    environment:
      - ZOO_MY_ID=3
  api:
    image: nuvla/api:test
    restart: unless-stopped
    ports:
      - "8200:8200"
    environment:
      - ES_HOST=es
      - ES_PORT=9300
      - ZK_ENDPOINTS=zk:2181
      - SUPER_PASS=supeRsupeR
    labels:
      - "traefik.enable=true"
      - "traefik.backend=api"
      - "traefik.backend.healthcheck.path=/api/cloud-entry-point"
      - "traefik.frontend.headers.customRequestHeaders=nuvla-authn-info:"
      - "traefik.frontend.rule=PathPrefix:/api"
      - "traefik.frontend.priority=20"
  ui:
    image: nuvla/ui:test
    restart: unless-stopped
    ports:
      - "80"
    labels:
      - "traefik.enable=true"
      - "traefik.backend=ui"
      - "traefik.backend.healthcheck.path=/ui/index.html"
      - "traefik.frontend.headers.customRequestHeaders=nuvla-authn-info:"
      - "traefik.frontend.rule=PathPrefix:/"
      - "traefik.frontend.priority=10"
  job-executor:
    image: nuvla/job:test
    restart: unless-stopped
    entrypoint: /app/job/src/scripts/job_executor.py
    command: --api-url http://api:8200 --api-insecure --api-user super --api-pass supeRsupeR --zk-hosts zk:2181 --es-hosts es
  job-dist-dummy:
    image: nuvla/job:test
    restart: unless-stopped
    entrypoint: /app/job/src/scripts/job_distributor_dummy_test_action.py
    command: --api-url http://api:8200 --api-insecure --api-user super --api-pass supeRsupeR --zk-hosts zk:2181
  job-dist-jobs-cleanup:
    image: nuvla/job:test
    restart: unless-stopped
    entrypoint: /app/job/src/scripts/job_distributor_jobs_cleanup.py
    command: --api-url http://api:8200 --api-insecure --api-user super --api-pass supeRsupeR --zk-hosts zk:2181
