version: '3'
services:
  proxy:
    image: traefik:latest
    restart: unless-stopped
    command: --api --web --docker --docker.exposedByDefault=false --loglevel=info
    volumes:
     - /var/run/docker.sock:/var/run/docker.sock:ro
     - ./traefik/traefik.toml:/traefik.toml
    ports:
     - "80:80"
     - "8080:8080"
  es:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.2.4
    restart: unless-stopped
    expose:
     - "9200"
     - "9300"
    environment:
     - cluster.name=elasticsearch
     - xpack.security.enabled=false
     - discovery.type=single-node
     - "ES_JAVA_OPTS=-Xms2048m -Xmx2048m"
  zk:
    image: zookeeper:latest
    restart: unless-stopped
    expose:
     - "2181"
    environment:
     - ZOO_MY_ID=3
  api:
    image: nuvla/api:0.0.1-SNAPSHOT
    restart: unless-stopped
    ports:
     - "8200"
    environment:
     - ZK_ENDPOINTS="zk:2181"
     - ES_HOST=es
     - ES_PORT=9300
    labels:
     - "traefik.enable=true"
     - "traefik.backend=api"
     - "traefik.frontend.rule=PathPrefix:/api"
     - "traefik.frontend.priority=20"
  ui:
    image: nuvla/ui:0.0.1-SNAPSHOT
    restart: unless-stopped
    ports:
     - "80"
    labels:
     - "traefik.enable=true"
     - "traefik.backend=ui"
     - "traefik.frontend.rule=PathPrefix:/"
     - "traefik.frontend.priority=10"
#  job:
#    image: nuvla/job:0.0.1-SNAPSHOT
#    restart: unless-stopped

