name: release-please

on:
  push:
    branches:
      - master

permissions:
  contents: write
  pull-requests: write

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - uses: google-github-actions/release-please-action@v3
        id: release
        with:
          release-type: simple
          changelog-types: '[{"type":"deps","section":"Dependencies","hidden":false},{"type":"feat","section":"Features","hidden":false},{"type":"fix","section":"Bug Fixes","hidden":false},{"type":"chore","section":"Miscellaneous","hidden":false}]'
      - uses: actions/checkout@v2
        if: ${{ steps.release.outputs.release_created }}
      - name: Zip Folder
        if: ${{ steps.release.outputs.release_created }}
        run: zip -r ${{ github.event.repository.name }}.zip prod -x "target" "secrets" "*.iml"  "*.log*" 
      - name: Upload Release Artifact
        if: ${{ steps.release.outputs.release_created }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run:
          gh release upload ${{ steps.release.outputs.tag_name }} ./${{ github.event.repository.name }}.zip
  notify:
    name: Post Workflow Status To Slack
    needs:
      - release
    runs-on: ubuntu-latest
    steps:
      - run: |
        echo "${{needs.release.outputs.release_created}}"
        echo "${{needs.release.outputs.*}}"
      