name: release-please

on:
  push:
    branches:
      - master

permissions:
  contents: write
  pull-requests: write

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - uses: google-github-actions/release-please-action@v3
        with:
          release-type: simple
          bootstrap-sha: 0a7eb10017eea7a2d0057b4db6264609be7c7073
          release-as: 3.0.0
          